// Differential tests: every program in this folder has an input (`.in`) and
// the output a real toolchain produced for it (`.out`, generated by
// `apps/web/scripts/visualizer-corpus.mjs` with g++, javac/java and CPython).
// Each engine must print exactly the same output.

import { loadPyodide, type PyodideAPI } from 'pyodide'
import { beforeAll, describe, expect, it } from 'vitest'

import {
  defaultTraceLimits,
  type ExecutionTrace,
  type TraceRequest,
  type VisualizerLanguage,
} from '../../trace'
import { runCpp } from '../cpp'
import { runJava } from '../java'
import { installTracer, runPython } from '../python'

// Every corpus file as text, keyed by its path relative to this folder.
const files = import.meta.glob<string>(['./cpp/*', './java/*', './python/*'], {
  query: '?raw',
  import: 'default',
  eager: true,
})

const extensions: Record<VisualizerLanguage, string> = {
  cpp: '.cpp',
  java: '.java',
  python: '.py',
}

type Case = { name: string; code: string; input: string; expected: string }

function cases(language: VisualizerLanguage): Case[] {
  const extension = extensions[language]
  const prefix = `./${language}/`
  return Object.keys(files)
    .filter((file) => file.startsWith(prefix) && file.endsWith(extension))
    .sort()
    .map((file) => {
      const base = file.slice(0, -extension.length)
      return {
        name: base.slice(prefix.length),
        code: files[file] ?? '',
        input: files[`${base}.in`] ?? '',
        expected: files[`${base}.out`] ?? '',
      }
    })
}

const limits = { ...defaultTraceLimits, timeMs: 10_000 }

function describeFailure(trace: ExecutionTrace) {
  return trace.error === undefined
    ? ''
    : `${trace.error.title}: ${trace.error.message} (line ${trace.error.line ?? '?'})`
}

let pyodide: PyodideAPI | null = null

const runners: Record<
  VisualizerLanguage,
  (request: TraceRequest) => ExecutionTrace
> = {
  cpp: runCpp,
  java: runJava,
  python: (request) => {
    if (pyodide === null) throw new Error('Pyodide is not loaded')
    return runPython(pyodide, request)
  },
}

beforeAll(async () => {
  if (cases('python').length > 0) {
    pyodide = await loadPyodide()
    installTracer(pyodide)
  }
}, 60_000)

for (const language of ['cpp', 'java', 'python'] as const) {
  const list = cases(language)
  if (list.length === 0) continue
  describe(`${language} corpus`, () => {
    for (const item of list) {
      it(`${item.name} prints what the real toolchain printed`, () => {
        const trace = runners[language]({
          language,
          code: item.code,
          input: item.input,
          limits,
        })
        expect(describeFailure(trace)).toBe('')
        expect(trace.stdout).toBe(item.expected)
        expect(trace.steps.length).toBeGreaterThan(0)
      })
    }
  })
}
